### ISSUE TITLE
sotdText in organisation_config.js heeft een verwijzing naar een niet configureerbaar gremium

### ISSUE THREAD

**Issue by mvb-nerdzone** [Logius-standaarden/ep-algemeen#4]
De variabele `sotdTEXT` in [organisation-config.js](/Logius-standaarden/ep-algemeen/blob/ontwikkeling/ReSpec/organisation-config.js) heeft op twee plaatsen een verwijzing naar een gremium TO (Technisch Overleg). Dat is voor e-procurement een niet bestaand gremium, dus zouden we het graag aanpasbaar zien.

**Comment by mvb-nerdzone** [comment]
Zie ook →

- Logius-standaarden/ep-basisfactuur-rijk#1
- Logius-standaarden/ep-basisorder-rijk#2
- Logius-standaarden/ReSpec-template#3

**Comment by mvb-nerdzone** [comment]
Was ff een uitzoekwerkje maar, maar het is gefikst.

Wat is er gedaan:
* Volgorde van de configuratieitems in de index.html van de bijbehorende ReSpec-publicatie(s) veranderd (omgedraaid
  * éérst de config.js, dan de organisation-config.js (waarschijnlijk niet nodig)
  * `respecConfig = {...respecConfig, ...organisationConfig}` in plaats van `respecConfig = {...organisationConfig, ...respecConfig}`
* twee variabelen `sotdCommitteeNameNL` en `sotdCommitteeNameEN` toegevoegd in config.js van de bijbehorende ReSpec-publicatie(s) 
* deze variabelen als [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) opgenomen in de variable `sotdText` in `organisation-config.js`.

**Comment by sanderke** [comment]
De volgorde van het laden was bewust gekozen zodat variabelen in `respecConfig` de gelijknamige in `organisationConfig` overschrijven. Hierdoor kan je documentspecifieke wijzigingen aanbrengen die je niet in de organisatieconfig wilt.

Door `sotdText` in de documentconfig te plaatsen is de tekst volledig aan te passen.

**Comment by mvb-nerdzone** [comment]
@sanderke -- beetje late reactie, maar dank nog voor de uitleg. Ik had al zo'n vermoeden dat het op die manier zou werken, maar omdat de `sotdText` voor het grootste deel wél standaard is, leek het me handig om alleen het gremium variabel te maken. Ik ga het weer omdraaien, dan heb ik mogelijk in de toekomst ook minder kans om tegen problemen hierdoor aan te lopen.

**Comment by mvb-nerdzone** [comment]
Fixed.
